import '../assets/css/main.css'
import '../assets/css/osu.css'

import '../assets/js/wave/RuntimeUtils.js'
import '../assets/js/wave/RuntimeCore.js'
import '../assets/js/colorize.js'
import '../assets/js/wave/AudioEngine.js'
import '../assets/js/wave/API/GetSongBpmApi.js'
import '../assets/js/wave/API/DeezerBpmApi.js'
import '../assets/js/wave/API/ReccoBeatsBpmApi.js'
import '../assets/js/wave/OnlineOsuBPM.js'
import '../assets/js/wave/WaveVariants.js'
import '../assets/js/wave/Cover2Anim.js'
import '../assets/js/wave/TweakedYMDesign.js'
import '../assets/js/wave/WebGLRuntime.js'
import '../assets/js/wave/MainOsu.js'
import '../assets/js/control/ControlPanelOsu.js'
import '../assets/index.js'
